version: 2

jobs:
  build:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
            - yarn-deps
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-deps-{{ checksum "yarn.lock" }}-{{ epoch }}
      - run:
          name: yarn build
          command: |
            export __BUILD_VERSION=$(cat versio.txt)

            if [ -z "$__BUILD_VERSION" ]
            then
              echo Build version is not specified.
              exit 1
            fi

            yarn build
      - store_artifacts:
          path: dist/server.js
